# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest PyGObject Pillow PyAudio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libao-dev libfftw3-dev librtlsdr-dev python3-pyaudio && git clone https://github.com/theori-io/nrsc5.git
    - name: Configure
      run: |
        cd nrsc5
        mkdir build
        cd build
        cmake ..
    - name: Compile
      working-directory: build
      run: make -j3
    - name: Install
      working-directory: build
      run: |
        sudo make install
        sudo ldconfig
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
